${_MAGNUM_STBIMAGECONVERTER_NO_BMP}provides=StbBmpImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_HDR}provides=StbHdrImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_JPEG}provides=StbJpegImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_PNG}provides=StbPngImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_TGA}provides=StbTgaImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_BMP}provides=BmpImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_HDR}provides=HdrImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_JPEG}provides=JpegImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_PNG}provides=PngImageConverter
${_MAGNUM_STBIMAGECONVERTER_NO_TGA}provides=TgaImageConverter

# [configuration_]
[configuration]
# Compression quality for JPEG output (0 - 1, 1 is the best). Corresponds to
# the same option in JpegImageConverter.
jpegQuality=0.8
# [configuration_]
